# ci-web/k8s-deployment.yaml
# ─────────────────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: capit-web
  namespace: default
spec:
  selector:
    app: capit-web
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capit-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capit-web
  template:
    metadata:
      labels:
        app: capit-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: capit-web
          image: ghcr.io/gill-sans/ci-api/capit-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: capit-web
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: capit-dev.mertenshome.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: capit-web
                port:
                  number: 80
